# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DK
subtitle: I love the way i chase my.
author: DK
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "http://danyinglin.github.io"
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: DK's
header-img: /img/post-bg-2015.jpg
email: dylin.fow@gmail.com
description: "I love the way I chase you."
keyword: "DK, DK's Blog, iOS, Apple, app"
signature: true #show signature
signature-img: /img/signature/white.png 

# 自动生成sitemap
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
search:
    path: search.xml
    field: post
    format: html
    limit: 10000

# SNS settings
# RSS: false
zhihu_username:     danyinglin
github_username:    danyinglin
jianshu_username:   11700e1a83c3

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

daovoice:
    enable: false
    app_id: bdc5c12d
    email: qq1187712426@gmail.com

# Disqus settings
disqus_username: ddddddk

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 7bd18cd14435f89a4dfb                            #生成的clientID
  clientSecret: 87b3c3f9d0aa37f71d64aac84331b2e5e769b3a1    #生成的clientSecret
  repo: danyinglin.github.io    #仓库名称
  owner: danyinglin    #github用户名
  admin: danyinglin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Analytics settings
# Baidu Analytics
ba_track_id: 2620e69674d25088f870bef114e8ff89
bd_site_verification: aifbHeRmzy

# Google Analytics
ga_track_id: 'UA-124238838-1'            # Format: UA-xxxxxx-xx
ga_domain: csjiabin.github.io
google_site_verification: Xk9YWz2-rBE9P5__qdWz3nUr4zb9bIDSdANHpezjB04


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I love the way I chase you."
sidebar-avatar: /img/about-DK-gentle.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "CSjiabin's Blog",
        href: "https://csjiabin.github.io"
    },{
        title: "Material Design",
        href: "https://material.io/"
    },{
        title: "BYQiu's Jianshu",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
    - README.md
    - sw.js

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/danyinglin/danyinglin.github.io.git
  branch: master
